name: Compile Wurst 1.21.1

on:
  push:
    branches: [ "1.21.1" ]
  pull_request:
    branches: [ "1.21.1" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'gradle'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # See samm parandab automaatselt kõik litsentsipäiste ja koodi vormingu vead
    - name: Fix code formatting and license headers
      run: ./gradlew spotlessApply

    - name: Build with Gradle
      run: ./gradlew build

    - name: Upload Compiled JAR
      uses: actions/upload-artifact@v4
      with:
        name: Wurst-1.21.1
        path: build/libs/*.jar
